# pyproject.toml
[project]
name = "sydweather-utils"
version = "0.2.1"
description = "Utilities for time-series weather/market feature engineering and splits"
readme = "README.md"
requires-python = ">=3.9"
# ... keep your existing metadata/deps ...
